name: Node.js Package
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: NPM - Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: NPM - Install
        run: npm install

      - name: NPM - Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

# will required if we build the source
#      - name: Upload artifacts
#        uses: actions/upload-artifact@master
#        with:
#          name: Assets
#          path: ./dist